import os
from docx import Document
from docx.shared import Inches, Pt
from pptx import Presentation
from pptx.util import Inches as PptInches, Pt as PptPt
try:
    from fpdf import FPDF
except ImportError:
    FPDF = None # Fallback or handle missing dep
from datetime import datetime

class ResearchExporter:
    """Exports research insights into professional documents (Word, PPT, PDF)."""
    
    def __init__(self, export_dir: str):
        self.export_dir = export_dir
        os.makedirs(self.export_dir, exist_ok=True)

    def export_to_word(self, node: dict) -> str:
        """Generates a detailed, academically structured Word document."""
        doc = Document()
        
        # Title
        title = doc.add_heading(node.get("title", "Research Report"), 0)
        title.alignment = 1 # Center
        
        # Abstract Section
        doc.add_heading("I. Executive Summary", level=1)
        doc.add_paragraph(node.get("content", "No summary available.").strip())
        
        # Details / Content
        doc.add_heading("II. Technical Analysis", level=1)
        content = node.get("content", "")
        if len(content) > 1000:
             doc.add_paragraph(content[:2000] + "...")
        else:
             doc.add_paragraph(content)

        # Metadata & Citations
        doc.add_heading("III. Metadata & Provenance", level=1)
        metadata = node.get("metadata", {})
        table = doc.add_table(rows=1, cols=2)
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Field'
        hdr_cells[1].text = 'Value'
        
        for key, val in metadata.items():
            if key in ["embedding", "vector", "content", "summary"]: continue
            row_cells = table.add_row().cells
            row_cells[0].text = str(key).capitalize()
            row_cells[1].text = str(val)

        doc.add_page_break()
        doc.add_heading("IV. Agent Bibliography", level=1)
        doc.add_paragraph(f"Generated by RESEARCHAI Autonomous Swarm\nTimestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        filename = f"{node['id']}_formal_report.docx"
        filepath = os.path.join(self.export_dir, filename)
        doc.save(filepath)
        return filename

    def export_to_ppt(self, node: dict) -> str:
        """Generates an executive board-ready PowerPoint presentation."""
        prs = Presentation()
        
        # Title Slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = node.get("title", "Research Insight")
        slide.placeholders[1].text = f"Autonomous Intelligence Analysis\n{datetime.now().strftime('%B %d, %Y')}"
        
        # Key Highlights Slide
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Strategic Findings"
        tf = slide.placeholders[1].text_frame
        tf.text = node.get("title", "")
        
        content = node.get("content", "")
        for line in content.split(". ")[:5]:
            if len(line) > 5:
                p = tf.add_paragraph()
                p.text = line.strip() + "."
                p.level = 0

        # Technical Metadata Slide
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = "System Metadata"
        metadata = node.get("metadata", {})
        meta_text = "\n".join([f"• {k}: {v}" for k, v in list(metadata.items())[:8] if k not in ["embedding", "vector"]])
        
        left = PptInches(1)
        top = PptInches(2)
        width = PptInches(8)
        height = PptInches(5)
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.text = meta_text
        
        filename = f"{node['id']}_executive_slides.pptx"
        filepath = os.path.join(self.export_dir, filename)
        prs.save(filepath)
        return filename

    def export_to_pdf(self, node: dict) -> str:
        """Generates a premium PDF brief using FPDF2."""
        filename = f"{node['id']}_brief.pdf"
        filepath = os.path.join(self.export_dir, filename)

        if FPDF is None:
            # Fallback to reportlab if FPDF is missing (legacy support)
            from reportlab.pdfgen import canvas
            from reportlab.lib.pagesizes import letter
            c = canvas.Canvas(filepath, pagesize=letter)
            c.drawString(72, 750, node.get("title", "Research Brief"))
            c.save()
            return filename

        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Helvetica", "B", 24)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(0, 20, "RESEARCH_AI BRIEF", ln=True, align="C")
        pdf.set_draw_color(0, 245, 255) # Accent color cyan
        pdf.line(10, 30, 200, 30)
        pdf.ln(15)

        # Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.multi_cell(0, 10, node.get("title", "Untitled Node"))
        pdf.ln(5)

        # Metadata Bar
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"ID: {node['id']} | TYPE: {node.get('type', 'PAWN').upper()} | EXPORTED: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
        pdf.ln(10)

        # Body Content
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        content = node.get("content", "No content available.")
        pdf.multi_cell(0, 6, content)

        # Footer
        pdf.set_y(-30)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 10, f"Confidential Intelligence Output - {node['id']}", align="C")

        pdf.output(filepath)
        return filename
