from .base import BaseAgent
from datetime import datetime
import os

class SynthesisAgent(BaseAgent):
    """Agent responsible for high-level research synthesis and automated paper writing."""
    
    def __init__(self, model="gemma", experience_store=None):
        super().__init__(model=model, experience_store=experience_store)

    def write_paper_section(self, section_name: str, context: str, instructions: str) -> str:
        """Generates a specific academic section based on research context."""
        prompt = f"""
Write the '{section_name}' of a publishable academic paper.

RESEARCH CONTEXT:
{context}

INSTRUCTIONS:
{instructions}

Ensure formal academic tone, citations in [Paper ID] format, and rigorous analysis.
"""
        return self.ask_llm(prompt, "You are a world-class academic writer (Science/Nature style).")

    def synthesize_full_report(self, papers: list) -> str:
        """Executes the full pipeline: Intro -> Related Work -> Analysis -> Discussion."""
        self.log(f"Synthesizing full report from {len(papers)} sources.")
        
        context = "\n\n".join([
            f"ID: {p['id']}\nTitle: {p['title']}\nClaims: {p.get('metadata', {}).get('structure', {}).get('claims', [])}\nSummary: {p['content'][:500]}"
            for p in papers
        ])

        # 1. Introduction
        intro = self.write_paper_section("Introduction", context, "Define the problem space, background, and the significance of current findings.")
        
        # 2. Related Work
        related = self.write_paper_section("Related Work", context, "Group papers by methodology and compare their underlying assumptions.")
        
        # 3. Discussion & Synthesis
        discussion = self.write_paper_section("Discussion", context, "Synthesize a new hypothesis that resolves existing contradictions or fills a detected gap.")

        full_paper = f"""# RESEARCH SYNTHESIS: {datetime.now().strftime('%Y-%m-%d')}
AUTO-GENERATED BY RESEARCHAI SWARM

## ABSTRACT
{intro[:500]}...

## 1. INTRODUCTION
{intro}

## 2. TRENDS & RELATED WORK
{related}

## 3. SYNTHESIS & HYPOTHESIS
{discussion}

## REFERENCES
{chr(10).join([f"- [{p['id']}] {p['title']}" for p in papers])}
"""
        return full_paper

    def format_ieee(self, paper_data: dict) -> str:
        """Converts paper data into an IEEEtran LaTeX document."""
        references = paper_data.get('references', [])
        refs_latex = "\n".join([f"\\bibitem{{ref{i}}} {ref['title']}" for i, ref in enumerate(references)])
        
        return f"""
\\documentclass[conference]{{IEEEtran}}
\\usepackage{{cite}}
\\usepackage{{amsmath,amssymb,amsfonts}}

\\begin{{document}}

\\title{{{paper_data.get('title', 'Sovereign Research Report')}}}

\\author{{
\\IEEEauthorblockN{{RESEARCHAI Autonomous Swarm}}
\\IEEEauthorblockA{{Institutional Intelligence Node}}
}}

\\maketitle

\\begin{{abstract}}
{paper_data.get('abstract', 'Autonomous research synthesis.')}
\\end{{abstract}}

\\section{{Introduction}}
{paper_data.get('intro', '')}

\\section{{Related Work}}
{paper_data.get('related', '')}

\\section{{Methodology}}
{paper_data.get('method', '')}

\\section{{Results & Analysis}}
{paper_data.get('results', '')}

\\section{{Conclusion}}
{paper_data.get('conclusion', '')}

\\bibliographystyle{{IEEEtran}}
\\begin{{thebibliography}}{{1}}
{refs_latex}
\\end{{thebibliography}}

\\end{{document}}
"""

    def format_nature(self, paper_data: dict) -> str:
        """Converts paper data into a Nature-style narrative report."""
        references = paper_data.get('references', [])
        refs_md = "\n".join([f"{i+1}. {ref['title']} ({ref.get('id', '')})" for i, ref in enumerate(references)])
        
        return f"""
# {paper_data.get('title', 'Sovereign Research Report')}

**Abstract**
{paper_data.get('abstract', '')}

**Main**
{paper_data.get('intro', '')}

**Methods**
{paper_data.get('method', '')}

**Results**
{paper_data.get('results', '')}

**Discussion**
{paper_data.get('discussion', '')}

**References**
{refs_md}
"""

    def generate_rebuttal(self, paper_content: str, reviews: str) -> str:
        """Generates a professional academic response to peer review comments."""
        self.log("Generating AI peer-review rebuttal...")
        
        prompt = f"""
You are the lead author of an academic paper. Respond to these peer reviews with precision, respect, and technical defense.

PAPER CONTENT:
{paper_content[:2000]}

PEER REVIEWS:
{reviews}

Write a formal rebuttal letter:
1. Address each concern point-by-point.
2. Defend contribution where valid.
3. Acknowledge and propose fixes for valid issues.
4. Maintain a tone of academic excellence.
"""
        rebuttal = self.ask_llm(prompt, "You are a senior academic defender with 100+ publications.")
        self.reflect("Review Rebuttal", reviews[:500], 0.95)
        return rebuttal
